#!/bin/bash

# git remote add dep-mruby https://github.com/mruby/mruby.git
# git subtree add --prefix=src/mruby --squash dep-mruby master

git subtree pull --prefix=src/mruby --squash dep-mruby master

